/*  OpenFIRE Web App - board data helpers (src/boards/OpenFIREshared.h -> OpenFIREshared).

    OF.BUILD is injected by scripts/webapp_build.py:
        { target: 'device' | 'site', board: '<board>' | null }
    Without it (webapp folder served as is during development) the target is 'site'.

    On the lightgun (target 'device') only its own board is in OpenFIREshared and its
    picture is inside app.js; the site loads the picture of a board when it is shown,
    from the script with the same name in boards/pics/ (rpipico.svg -> boards/pics/rpipico.js).
    Scripts, unlike fetch(), also load when the page is opened as a local file (file://).
    Both register the SVG text generated by scripts/build_board_pics.py:
        OF.BoardPictures["rpipico.svg"] = "<svg ...>";

    Board pictures are inline SVG: the pin circles (id "OF_pin<gpio>", style "opacity:0")
    are made visible while the pointer is over a pin description.
    Each picture lives in the shadow root of its host element: the <style> blocks and ids
    of the SVG files (.st0, .st1...) stay private, so several pictures can be on the page.
*/
(function (root) {
    'use strict';

    const OF = root.OF = root.OF || {};
    const scriptLoads = new Map();

    /** Loads a script once. Resolves to true when it ran, false when it could not be loaded. */
    function loadScript(url) {
        if (!scriptLoads.has(url)) {
            const loading = new Promise((resolve) => {
                const doc = root.document;
                if (!doc) { resolve(false); return; }
                const script = doc.createElement('script');
                script.src = url;
                script.async = true;
                script.onload = () => resolve(true);
                script.onerror = () => {
                    script.remove();
                    scriptLoads.delete(url); // a later attempt may succeed
                    resolve(false);
                };
                (doc.head || doc.documentElement).append(script);
            });
            scriptLoads.set(url, loading);
        }
        return scriptLoads.get(url);
    }

    function shared() {
        return root.OpenFIREshared || (typeof OpenFIREshared !== 'undefined' ? OpenFIREshared : null);
    }

    function build() {
        return OF.BUILD || { target: 'site', board: null };
    }

    const Boards = {
        get shared() { return shared(); },
        get build() { return build(); },
        get isDevice() { return build().target === 'device'; },

        /** Boards listed in "Compatible boards" (generic ones are hidden). */
        list() {
            const S = shared();
            return Object.keys(S.boardsBoxPositions).filter((board) => !board.includes('generic'));
        },

        /** Board to use for the data maps: unknown boards fall back to the generic layout. */
        resolve(board) {
            const S = shared();
            if (board && S.boardsBoxPositions[board]) return board;
            if (board && board.includes('rp2350') && S.boardsBoxPositions['generic-rp2350']) return 'generic-rp2350';
            return 'generic';
        },

        displayName(board) {
            const names = shared().boardNames || {};
            return names[board] || board || '';
        },

        /** Architecture whose name is part of the board name ("esp32-s3"), else the first one (RP2040/235X). */
        arch(board) {
            const archs = shared().boardArchs;
            let found = archs[0];
            for (const arch of archs.slice(1)) {
                if (arch && board && board.includes(arch) && (found === archs[0] || arch.length > found.length))
                    found = arch;
            }
            return found;
        },

        /** ESP32 family (board name containing "esp32"). */
        isEsp32(board) {
            return !!board && board.includes('esp32');
        },

        /** Capability bitmap of every GPIO: board specific map, else the architecture map. */
        capabilities(board) {
            const maps = shared().mcuCapableMaps;
            return maps[board] || maps[this.arch(board)] || [];
        },

        boxPositions(board) {
            return shared().boardsBoxPositions[this.resolve(board)] || [];
        },

        defaultPins(board) {
            return shared().boardsPresetsMap[board] || [];
        },

        altPresets(board) {
            return (shared().boardsAltPresets || {})[board] || [];
        },

        /** Picture file of a board in boards.qrc (the key of OF.BoardPictures). */
        pictureName(board) {
            const images = shared().boardImagesMap || {};
            return images[board] || images.generic || 'generic.svg';
        },

        /** Script of the picture: same name, extension .js. */
        pictureUrl(board) {
            return 'boards/pics/' + this.pictureName(board).replace(/\.[^./]*$/, '') + '.js';
        },

        /**
         * Shows the board picture inside `host` (inline SVG in its shadow root).
         * Resolves to the <svg> element, or null when unavailable or replaced meanwhile.
         */
        async showPicture(host, board) {
            host.dataset.board = board;
            const text = await this.loadPicture(board);
            if (host.dataset.board !== board) return null;
            const root = host.shadowRoot || host.attachShadow({ mode: 'open' });
            root.innerHTML = '<style>:host{display:block}svg{display:block;width:100%;height:100%}</style>' + text;
            const svg = root.querySelector('svg');
            if (!svg) return null;
            svg.removeAttribute('width');
            svg.removeAttribute('height');
            if (!svg.hasAttribute('preserveAspectRatio')) svg.setAttribute('preserveAspectRatio', 'xMidYMid meet');
            return svg;
        },

        /** Shows (on = true) or hides the circle drawn over a pin of the picture shown in `host`. */
        highlightPin(host, gpio, on) {
            const root = host && host.shadowRoot;
            const pin = root && root.getElementById(`OF_pin${gpio}`);
            if (!pin) return false;
            if (pin.dataset.ofOpacity === undefined) pin.dataset.ofOpacity = pin.style.opacity;
            pin.style.opacity = on ? '1' : pin.dataset.ofOpacity;
            return true;
        },

        /** SVG source text of the board picture. Resolves to '' when unavailable. */
        async loadPicture(board) {
            const pictures = () => OF.BoardPictures || {};
            // The lightgun page has only the picture of its own board, inside app.js.
            if (this.isDevice) return Object.values(pictures())[0] || '';
            const name = this.pictureName(board);
            if (!(name in pictures())) await loadScript(this.pictureUrl(board));
            return pictures()[name] || '';
        },
    };

    OF.Boards = Boards;
})(typeof globalThis !== 'undefined' ? globalThis : this);
