/*  OpenFIRE Web App: protocol tests against the mock firmware.

    Run from lightgun/webapp:   node --test tests/*.test.js
    Requires boards/OpenFIREshared.js generated by scripts/build_shared_js.py
    (a normal PlatformIO build regenerates it).
*/
'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const { MockFirmware, MemoryLink, createMemoryTransport, crc8 } = require('./mock-firmware.js');

const WEBAPP = path.join(__dirname, '..');

function loadScript(relative) {
    vm.runInThisContext(fs.readFileSync(path.join(WEBAPP, relative), 'utf8'), { filename: relative });
}

loadScript('boards/OpenFIREshared.js');
vm.runInThisContext('globalThis.OpenFIREshared = OpenFIREshared;');
loadScript('js/core/transport.js');
loadScript('js/core/protocol.js');

const OF = globalThis.OF;
const S = globalThis.OpenFIREshared;
const C = S.serialCmdTypes_e;

if (!S.boolTypes_Strings)
    throw new Error('boards/OpenFIREshared.js is outdated: regenerate it with scripts/build_shared_js.py');

// Quiet expected warnings; keep them available with OF_TEST_VERBOSE=1.
if (!process.env.OF_TEST_VERBOSE) {
    console.warn = () => {};
    console.debug = () => {};
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function setup(linkOptions = {}, firmwareOptions = {}) {
    const link = new MemoryLink(linkOptions);
    const firmware = new MockFirmware(S, link, firmwareOptions);
    firmware.start();
    const protocol = new OF.Protocol({ shared: S });
    const events = [];
    protocol.on('event', (command, payload) => events.push({ command, payload: Array.from(payload) }));
    const closed = [];
    protocol.on('closed', (reason) => closed.push(reason));
    const transport = createMemoryTransport(OF, link);
    await protocol.connect(transport);
    return { link, firmware, protocol, transport, events, closed };
}

async function teardown(ctx) {
    ctx.link.connected = false;
    await ctx.firmware.stop();
    if (ctx.transport.isOpen)
        await ctx.transport.close();
}

// The firmware ignores a new dock while a session is active (as with the Qt App,
// which always disconnects and reopens the port before docking again).
async function redock(ctx) {
    await ctx.protocol.disconnect();
    const transport = createMemoryTransport(OF, ctx.link);
    ctx.transport = transport;
    await ctx.protocol.connect(transport);
    return ctx.protocol.getSettings();
}

async function waitUntil(predicate, timeoutMs = 3000) {
    const started = Date.now();
    while (!predicate()) {
        if (Date.now() - started > timeoutMs)
            return false;
        await sleep(5);
    }
    return true;
}

// ===== Framing ==============================================================

test('frame encoding matches the firmware CRC-8 and layout', () => {
    const payload = Uint8Array.from([0x52, 0x75, 0x6D, 0x62, 0x00, 0x01, 0x01]);
    const frame = OF.ProtocolUtils.buildFrame(0x00, C.sCommitToggles, 7, payload);
    assert.equal(frame[0], 0xA5);
    assert.equal(frame[1], 0x5A);
    assert.equal(frame[3], C.sCommitToggles);
    assert.equal(frame[4], 7);
    assert.equal(frame[5], payload.length);
    assert.equal(frame[frame.length - 1], crc8(frame.subarray(2, frame.length - 1)));
    assert.equal(OF.ProtocolUtils.buildFrame(0, 1, 1, new Uint8Array(201)), null);
});

test('profile and TinyUSB codecs keep the C struct layout', () => {
    const codec = new OF.ProtocolCodec(S);
    const profile = Object.assign(codec.createProfile(), {
        topOffset: -12, TLled: 1023.5, irSensitivity: 2, color: 0x12AB34, name: 'Arcade Room CRT!!'
    });
    const raw = codec.encodeProfile(profile);
    assert.equal(raw.length, 68);
    const view = new DataView(raw.buffer);
    assert.equal(view.getInt32(0, true), -12);
    assert.equal(view.getFloat32(16, true), 1023.5);
    assert.equal(view.getUint32(32, true), 2);
    assert.equal(view.getUint32(48, true), 0x12AB34);
    assert.equal(OF.ProtocolUtils.decodeCString(raw.subarray(52)), 'Arcade Room CRT'); // 15 chars + NUL

    const usb = codec.encodeTinyUSB({ id: 0x1234, name: 'FIRECon P3' });
    assert.equal(usb.length, 18);
    assert.deepEqual(codec.decodeTinyUSB(usb), { id: 0x1234, name: 'FIRECon P3' });
});

// ===== Docking and synchronization =========================================

test('dock and read all settings', async () => {
    const ctx = await setup();
    try {
        const progress = [];
        ctx.protocol.on('progress', (p) => progress.push(p));
        const result = await ctx.protocol.getSettings();
        assert.equal(result.ok, true, JSON.stringify(result));
        assert.equal(ctx.protocol.sessionActive, true);

        assert.equal(result.board.version, '6.2-abcdef0');
        assert.equal(result.board.type, 'esp32-s3-devkitc-1');
        assert.equal(result.board.arch, 'esp32-s3');
        assert.equal(result.board.cameraError, false);

        const cfg = result.config;
        assert.deepEqual(cfg.tinyUSB, { id: 1, name: 'FIRECon P1' });
        assert.deepEqual(cfg.toggles, Array.from(ctx.firmware.toggles, (b) => b !== 0));
        for (let i = 0; i < S.settingsTypes_e.settingsTypesCount; ++i)
            assert.equal(cfg.settings[i], ctx.firmware.getSetting(i));
        for (let i = 0; i < 13; ++i)
            assert.deepEqual(cfg.buttons[i], Array.from(ctx.firmware.backupButtonDesc.subarray(i * 6, i * 6 + 6)));
        assert.deepEqual(cfg.buttons[13], [0, 0, 0, 0, 0, 0], 'Home is not managed by the App');
        assert.equal(cfg.profiles.length, 4);
        assert.equal(cfg.selectedProfile, 0);
        assert.equal(cfg.profiles[2].name, 'Profile Start');
        assert.equal(cfg.profiles[1].topOffset, 11);
        assert.equal(cfg.profiles[3].leftOffset, -33);
        assert.equal(cfg.profiles[0].TRled, 6656.25);
        assert.equal(cfg.profiles[3].color, 0xFF00FF);
        assert.deepEqual(cfg.pins, new Array(S.boardInputs_e.boardInputsCount).fill(-1), 'custom pins disabled');

        assert.deepEqual(progress[0], { range: 6 });
        assert.equal(progress[progress.length - 1].value, 6);
    } finally {
        await teardown(ctx);
    }
});

test('custom pins are read when enabled, camera error flag is decoded', async () => {
    const ctx = await setup({}, { camNotAvailable: true, boardType: 'rpipico' });
    try {
        ctx.firmware.toggles[S.boolTypes_e.customPins] = 1;
        ctx.firmware.loadPresets();
        ctx.firmware.pins[S.boardInputs_e.btnTrigger] = 3;

        const result = await ctx.protocol.getSettings();
        assert.equal(result.ok, true);
        assert.equal(result.board.arch, 'rp2040_235X');
        assert.equal(result.board.cameraError, true);
        assert.deepEqual(result.config.pins, Array.from(ctx.firmware.pins));
        assert.equal(result.config.pins[S.boardInputs_e.btnTrigger], 3);
    } finally {
        await teardown(ctx);
    }
});

test('dock times out when nothing answers', async () => {
    const link = new MemoryLink();
    const protocol = new OF.Protocol({ shared: S });
    const transport = createMemoryTransport(OF, link);
    await protocol.connect(transport);
    const started = Date.now();
    const result = await protocol.getSettings();
    assert.equal(result.ok, false);
    assert.equal(result.error, 'dock_timeout');
    assert.equal(result.rebootSuggested, true);
    assert.ok(Date.now() - started >= 2900);
    const dockWrites = transport.writes.filter((w) => w.length === 2 && w[0] === C.sDock1 && w[1] === C.sDock2);
    assert.equal(dockWrites.length, 4, 'dock retried every 750 ms for 3 s');
    await transport.close();
});

test('device events are delivered while docked and during record streams', async () => {
    const ctx = await setup();
    try {
        assert.equal((await ctx.protocol.getSettings()).ok, true);
        ctx.firmware.queueEvent(C.sBtnPressed, Uint8Array.of(2));
        ctx.firmware.queueEvent(C.sTemperatureUpd, Uint8Array.of(41));
        assert.ok(await waitUntil(() => ctx.events.length >= 2));
        assert.deepEqual(ctx.events.slice(0, 2), [
            { command: C.sBtnPressed, payload: [2] },
            { command: C.sTemperatureUpd, payload: [41] }
        ]);

        // An event injected in the middle of a record stream must not break it.
        const original = ctx.firmware.sendResponse.bind(ctx.firmware);
        let injected = false;
        ctx.firmware.sendResponse = async (command, payload, final) => {
            if (!injected && command === C.sGetSettings) {
                injected = true;
                ctx.firmware.sendEvent(C.sBtnReleased, Uint8Array.of(2));
            }
            return original(command, payload, final);
        };
        const again = await redock(ctx);
        assert.equal(again.ok, true);
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sBtnReleased)));
    } finally {
        await teardown(ctx);
    }
});

// ===== Commit ===============================================================

test('commit round trip updates the firmware and keeps calibration geometry', async () => {
    const ctx = await setup();
    try {
        const loaded = await ctx.protocol.getSettings();
        assert.equal(loaded.ok, true);
        const original = loaded.config;
        const current = ctx.protocol.codec.cloneConfig(original);

        current.toggles[S.boolTypes_e.autofire] = true;
        current.toggles[S.boolTypes_e.customPins] = true;
        current.pins.fill(-1);
        current.pins[S.boardInputs_e.btnTrigger] = 5;
        current.pins[S.boardInputs_e.camSDA] = 8;
        current.settings[S.settingsTypes_e.rumbleStrength] = 128;
        current.settings[S.settingsTypes_e.customLEDcolor2] = 0xABCDEF;
        current.buttons[S.boardInputs_e.btnGunA] = [1, 0xB0, 1, 0xB1, 2, 3];
        current.profiles[1].name = 'Living Room';
        current.profiles[1].color = 0x00FFAA;
        current.profiles[1].irSensitivity = 2;
        current.profiles[1].layoutType = 1;
        current.profiles[1].topOffset = 9999; // must NOT be sent
        current.selectedProfile = 1;
        current.tinyUSB = { id: 3, name: 'FIRECon P3' };

        const progress = [];
        ctx.protocol.on('progress', (p) => progress.push(p));
        const result = await ctx.protocol.commitSettings(current, original);
        assert.equal(result.ok, true);
        assert.match(result.message, /Successfully saved/);
        assert.equal(ctx.protocol.commitNeedsRetry(), false);

        const fw = ctx.firmware;
        assert.equal(fw.savedCount, 1);
        assert.equal(fw.toggles[S.boolTypes_e.autofire], 1);
        assert.equal(fw.pins[S.boardInputs_e.btnTrigger], 5);
        assert.equal(fw.pins[S.boardInputs_e.camSDA], 8);
        assert.equal(fw.pins[S.boardInputs_e.btnGunA], -1);
        assert.equal(fw.getSetting(S.settingsTypes_e.rumbleStrength), 128);
        assert.equal(fw.getSetting(S.settingsTypes_e.customLEDcolor2), 0xABCDEF);
        assert.deepEqual(Array.from(fw.backupButtonDesc.subarray(6, 12)), [1, 0xB0, 1, 0xB1, 2, 3]);
        assert.equal(fw.getProfileName(1), 'Living Room');
        assert.equal(fw.getProfileU32(1, 12), 0x00FFAA);
        assert.equal(fw.getProfileU32(1, 8), 2);
        assert.equal(fw.getProfileU32(1, 10), 1);
        assert.equal(fw.getProfileI32(1, 0), 11, 'calibration geometry stays in the firmware');
        assert.equal(fw.currentProfile, 1);
        assert.deepEqual(fw.getUSB(), { id: 3, name: 'FIRECon P3' });
        assert.deepEqual(progress[0], { range: 8 });
        assert.equal(progress[progress.length - 1].value, 8);

        // Reading back returns exactly what was committed (except geometry).
        const reread = await redock(ctx);
        assert.equal(reread.ok, true);
        assert.equal(reread.config.profiles[1].name, 'Living Room');
        assert.equal(reread.config.pins[S.boardInputs_e.camSDA], 8);
    } finally {
        await teardown(ctx);
    }
});

test('pins are sent when custom pins are being disabled', async () => {
    const ctx = await setup();
    try {
        ctx.firmware.toggles[S.boolTypes_e.customPins] = 1;
        ctx.firmware.pins[S.boardInputs_e.btnTrigger] = 20;
        const loaded = await ctx.protocol.getSettings();
        const current = ctx.protocol.codec.cloneConfig(loaded.config);
        current.toggles[S.boolTypes_e.customPins] = false;

        const sent = [];
        ctx.link.filterToFirmware = (bytes) => { if (bytes.length > 6 && bytes[2] === 0) sent.push(bytes[3]); return bytes; };
        const result = await ctx.protocol.commitSettings(current, loaded.config);
        assert.equal(result.ok, true);
        assert.ok(sent.includes(C.sCommitPins));
        assert.equal(ctx.firmware.toggles[S.boolTypes_e.customPins], 0);
    } finally {
        await teardown(ctx);
    }
});

test('failed save is recoverable and retry succeeds without restarting', async () => {
    const ctx = await setup();
    try {
        const loaded = await ctx.protocol.getSettings();
        const current = ctx.protocol.codec.cloneConfig(loaded.config);
        current.settings[S.settingsTypes_e.rumbleInterval] = 777;

        ctx.firmware.failNextSave = true;
        const first = await ctx.protocol.commitSettings(current, loaded.config);
        assert.equal(first.ok, false);
        assert.equal(ctx.protocol.commitNeedsRetry(), true);
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sError && e.payload[0] === 0x82)));
        assert.equal(ctx.protocol.isOpen, true, 'port stays open for a recoverable error');

        const second = await ctx.protocol.commitSettings(current, loaded.config);
        assert.equal(second.ok, true);
        assert.equal(ctx.protocol.commitNeedsRetry(), false);
        assert.equal(ctx.firmware.getSetting(S.settingsTypes_e.rumbleInterval), 777);
    } finally {
        await teardown(ctx);
    }
});

test('reconnecting with a pending commit reports that a save is required', async () => {
    const ctx = await setup();
    try {
        const loaded = await ctx.protocol.getSettings();
        const current = ctx.protocol.codec.cloneConfig(loaded.config);
        ctx.firmware.failNextSave = true;
        assert.equal((await ctx.protocol.commitSettings(current, loaded.config)).ok, false);

        await ctx.protocol.disconnect();
        assert.ok(await waitUntil(() => !ctx.firmware.sessionActive));
        assert.equal(ctx.firmware.gunMode, 'docked', 'board stays docked with pending RAM');

        ctx.events.length = 0;
        const transport = createMemoryTransport(OF, ctx.link);
        ctx.transport = transport;
        await ctx.protocol.connect(transport);
        const again = await ctx.protocol.getSettings();
        assert.equal(again.ok, true);
        assert.ok(await waitUntil(() => ctx.events.some((e) =>
            e.command === C.sError && e.payload[0] === 0x82 && e.payload[1] === C.sGetProfile)));
        assert.equal(ctx.protocol.commitNeedsRetry(), true);
    } finally {
        await teardown(ctx);
    }
});

// ===== Robustness ==========================================================

test('lost ACKs and duplicate retransmissions are handled on both sides', async () => {
    const ctx = await setup();
    try {
        // Drop the App's first ACK for every record of sGetSettings: the firmware
        // retransmits the same frame, which the App must ACK again but ignore.
        const droppedAcks = new Set();
        ctx.link.filterToFirmware = (bytes) => {
            if (bytes.length === 7 && (bytes[2] & 3) === 3 && bytes[3] === C.sGetSettings) {
                const key = bytes[4];
                if (!droppedAcks.has(key)) { droppedAcks.add(key); return null; }
            }
            return bytes;
        };
        // Drop the firmware's first ACK for sCommitStart: the App retransmits.
        let droppedStartAck = false;
        ctx.link.filterToApp = (bytes) => {
            if (!droppedStartAck && bytes.length === 7 && (bytes[2] & 3) === 3 && bytes[3] === C.sCommitStart) {
                droppedStartAck = true;
                return null;
            }
            return bytes;
        };

        const loaded = await ctx.protocol.getSettings();
        assert.equal(loaded.ok, true);
        assert.ok(droppedAcks.size > 5);
        assert.equal(loaded.config.settings[S.settingsTypes_e.solenoidOffLength], 80);

        const result = await ctx.protocol.commitSettings(ctx.protocol.codec.cloneConfig(loaded.config), loaded.config);
        assert.equal(result.ok, true);
        assert.equal(droppedStartAck, true);
    } finally {
        await teardown(ctx);
    }
});

test('sync and commit survive random loss, corruption and fragmentation', async () => {
    const ctx = await setup({ seed: 4242, dropRate: 0.03, corruptRate: 0.02, maxChunk: 5, latency: 1 });
    try {
        const loaded = await ctx.protocol.getSettings();
        assert.equal(loaded.ok, true, JSON.stringify(loaded));
        const current = ctx.protocol.codec.cloneConfig(loaded.config);
        current.profiles[3].name = 'Noisy Link';
        current.settings[S.settingsTypes_e.holdToPauseLength] = 1234;
        const result = await ctx.protocol.commitSettings(current, loaded.config);
        assert.equal(result.ok, true);
        assert.equal(ctx.firmware.getProfileName(3), 'Noisy Link');
        assert.equal(ctx.firmware.getSetting(S.settingsTypes_e.holdToPauseLength), 1234);
        assert.ok(ctx.link.stats.dropped + ctx.link.stats.corrupted > 0);
    } finally {
        await teardown(ctx);
    }
});

// ===== Calibration, IR test and commands ===================================

test('desktop calibration: stages, values and completion', async () => {
    const ctx = await setup();
    try {
        assert.equal((await ctx.protocol.getSettings()).ok, true);
        ctx.events.length = 0;

        const sens = 1, layout = 0, profile = 2;
        assert.equal(await ctx.protocol.sendCommand(C.sCaliProfile, Uint8Array.of(C.sCaliStart, profile, sens + (layout << 4))), true);
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sCaliStageUpd)));
        assert.deepEqual(ctx.events[0], { command: C.sCurrentProf, payload: [profile] });
        assert.deepEqual(ctx.events[1], { command: C.sCaliStageUpd, payload: [0] });

        for (let stage = 1; stage <= 7; ++stage) {
            ctx.firmware.trigger = true;
            assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sCaliStageUpd && e.payload[0] === stage)),
                      `stage ${stage}`);
        }

        const info = ctx.events.filter((e) => e.command === C.sCaliInfoUpd);
        assert.deepEqual(info.map((e) => e.payload[0]), [1, 2, 3, 4, 5, 6]);
        const value = (e) => new DataView(Uint8Array.from(e.payload.slice(1)).buffer);
        assert.equal(value(info[0]).getInt32(0, true), 90);
        assert.equal(value(info[3]).getInt32(0, true), -7);
        assert.equal(value(info[4]).getFloat32(0, true), 1023.5);
        assert.equal(ctx.firmware.getProfileI32(profile, 0), 90);
        assert.equal(ctx.firmware.gunMode, 'docked');
    } finally {
        await teardown(ctx);
    }
});

test('desktop calibration cancelled from the App restores the profile', async () => {
    const ctx = await setup();
    try {
        assert.equal((await ctx.protocol.getSettings()).ok, true);
        ctx.events.length = 0;
        await ctx.protocol.sendCommand(C.sCaliProfile, Uint8Array.of(C.sCaliStart, 0, 0));
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sCaliStageUpd)));
        ctx.firmware.trigger = true;
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sCaliStageUpd && e.payload[0] === 1)));

        // Qt: CaliWindowRequestedExit -> SendCommand(serialTerminator)
        assert.equal(await ctx.protocol.sendCommand(C.serialTerminator), true);
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sCaliStageUpd && e.payload[0] === 7)));
        const stages = ctx.events.filter((e) => e.command === C.sCaliStageUpd).map((e) => e.payload[0]);
        assert.deepEqual(stages.slice(-2), [0, 7]);
        assert.equal(ctx.firmware.getProfileI32(0, 0), 10, 'offsets restored');
        assert.equal(ctx.protocol.isOpen, true);
    } finally {
        await teardown(ctx);
    }
});

test('a request during calibration yields a fatal sError and closes the port', async () => {
    const ctx = await setup();
    try {
        assert.equal((await ctx.protocol.getSettings()).ok, true);
        ctx.events.length = 0;
        await ctx.protocol.sendCommand(C.sCaliProfile, Uint8Array.of(C.sCaliStart, 0, 0));
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sCaliStageUpd)));
        await ctx.protocol.sendCommand(C.sTestRumble);
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sError && e.payload.length === 0)));
        assert.ok(await waitUntil(() => !ctx.protocol.isOpen));
    } finally {
        await teardown(ctx);
    }
});

test('IR test mode streams coordinates until disabled', async () => {
    const ctx = await setup();
    try {
        assert.equal((await ctx.protocol.getSettings()).ok, true);
        ctx.events.length = 0;
        assert.equal(await ctx.protocol.sendCommand(C.sIRTest, Uint8Array.of(1)), true);
        assert.ok(await waitUntil(() => ctx.events.filter((e) => e.command === C.sTestCoords).length >= 3));
        const coords = ctx.events.find((e) => e.command === C.sTestCoords);
        assert.equal(coords.payload.length, 48);
        assert.equal(await ctx.protocol.sendCommand(C.sIRTest, Uint8Array.of(0)), true);
        await sleep(150);
        const count = ctx.events.filter((e) => e.command === C.sTestCoords).length;
        await sleep(200);
        assert.equal(ctx.events.filter((e) => e.command === C.sTestCoords).length, count);
    } finally {
        await teardown(ctx);
    }
});

test('camera not available: IR test answers with sErrCam', async () => {
    const ctx = await setup({}, { camNotAvailable: true });
    try {
        assert.equal((await ctx.protocol.getSettings()).ok, true);
        ctx.events.length = 0;
        await ctx.protocol.sendCommand(C.sIRTest, Uint8Array.of(1));
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sError && e.payload[0] === C.sErrCam)));
        assert.equal(ctx.protocol.isOpen, true);
    } finally {
        await teardown(ctx);
    }
});

test('profile selection, test commands, disconnect and redock', async () => {
    const ctx = await setup();
    try {
        assert.equal((await ctx.protocol.getSettings()).ok, true);
        ctx.events.length = 0;
        assert.equal(await ctx.protocol.sendCommand(C.sCaliProfile, Uint8Array.of(C.sCaliProfile, 3)), true);
        assert.ok(await waitUntil(() => ctx.events.some((e) => e.command === C.sCurrentProf && e.payload[0] === 3)));
        assert.equal(ctx.firmware.currentProfile, 3);

        assert.equal(await ctx.protocol.sendCommand(C.sTestSolenoid), true);
        assert.ok(await waitUntil(() => ctx.firmware.lastTest === C.sTestSolenoid));

        await ctx.protocol.disconnect();
        assert.equal(ctx.protocol.isOpen, false);
        assert.ok(await waitUntil(() => ctx.firmware.gunMode === 'run'));

        const transport = createMemoryTransport(OF, ctx.link);
        ctx.transport = transport;
        await ctx.protocol.connect(transport);
        const again = await ctx.protocol.getSettings();
        assert.equal(again.ok, true);
        assert.equal(again.config.selectedProfile, 3);
    } finally {
        await teardown(ctx);
    }
});

test('reboot to bootloader and clear save memory', async () => {
    let ctx = await setup();
    try {
        const loaded = await ctx.protocol.getSettings();
        await ctx.protocol.rebootToBootloader(loaded.board.arch); // ESP32: framed command, no ACK wait
        assert.equal(ctx.protocol.isOpen, false);
        assert.ok(await waitUntil(() => ctx.firmware.rebootedToBootloader));
    } finally {
        await teardown(ctx);
    }

    ctx = await setup();
    try {
        await ctx.protocol.getSettings();
        ctx.firmware.toggles[S.boolTypes_e.autofire] = 1;
        assert.equal(await ctx.protocol.clearSaveMemory(), true);
        assert.equal(ctx.protocol.isOpen, false);
        assert.ok(await waitUntil(() => ctx.firmware.flashCleared));
        assert.equal(ctx.firmware.toggles[S.boolTypes_e.autofire], 0);
    } finally {
        await teardown(ctx);
    }
});

test('unexpected transport loss emits closed and fails pending waits', async () => {
    const ctx = await setup();
    try {
        assert.equal((await ctx.protocol.getSettings()).ok, true);
        ctx.link.connected = false; // nothing answers any more
        const pending = ctx.protocol.sendCommand(C.sTestLEDR);
        await sleep(50);
        ctx.transport.simulateLoss();
        assert.equal(await pending, false);
        assert.ok(await waitUntil(() => ctx.closed.length === 1));
        assert.equal(ctx.closed[0], 'device_lost');
        assert.equal(ctx.protocol.sessionActive, false);
    } finally {
        await teardown(ctx);
    }
});
