/*  OpenFIRE Web App: abandoned App sessions (page reload, WebSocket closed).

    Run from lightgun/webapp:   node --test --test-concurrency=1 tests/*.test.js
    Requires boards/OpenFIREshared.js generated by scripts/build_shared_js.py.
*/
'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const { MockFirmware, MemoryLink, createMemoryTransport } = require('./mock-firmware.js');

const WEBAPP = path.join(__dirname, '..');
const load = (relative) => vm.runInThisContext(fs.readFileSync(path.join(WEBAPP, relative), 'utf8'), { filename: relative });

load('boards/OpenFIREshared.js');
vm.runInThisContext('globalThis.OpenFIREshared = OpenFIREshared;');
load('js/core/transport.js');
load('js/core/protocol.js');

const OF = globalThis.OF;
const S = globalThis.OpenFIREshared;
const C = S.serialCmdTypes_e;

if (!process.env.OF_TEST_VERBOSE) {
    console.warn = () => {};
    console.debug = () => {};
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function waitUntil(predicate, timeoutMs = 4000) {
    const started = Date.now();
    while (!predicate()) {
        if (Date.now() - started > timeoutMs)
            return false;
        await sleep(5);
    }
    return true;
}

async function newApp(link) {
    const protocol = new OF.Protocol({ shared: S });
    const events = [];
    protocol.on('event', (command, payload) => events.push({ command, payload: Array.from(payload) }));
    const transport = createMemoryTransport(OF, link);
    await protocol.connect(transport);
    return { protocol, events, transport };
}

/// over: link used by the first App ('serial' = USB/dongle, 'web' = WebSocket).
/// webMode: the firmware also serves the WebSocket (OF_WebConfigModeActive).
async function setup({ over = 'serial', webMode = over === 'web' } = {}) {
    const serialLink = new MemoryLink();
    const webLink = webMode ? new MemoryLink() : null;
    const firmware = new MockFirmware(S, serialLink, { webLink });
    firmware.start();
    const link = over === 'web' ? webLink : serialLink;
    const app = await newApp(link);
    return { link, serialLink, webLink, firmware, app };
}

async function teardown(ctx) {
    ctx.serialLink.connected = false;
    if (ctx.webLink) ctx.webLink.connected = false;
    await ctx.firmware.stop();
}

/// Closes a WebSocket page the way OpenFIREweb.cpp reports it.
function closePage(ctx, app) {
    app.transport.simulateLoss();
    ctx.firmware.clientLost = true;
}

test('a reloaded App docks again over the abandoned session (raw re-dock)', async () => {
    const ctx = await setup();
    try {
        assert.equal((await ctx.app.protocol.getSettings()).ok, true);
        const firstSession = ctx.firmware.sessionCounter;
        ctx.app.transport.simulateLoss(); // page reloaded: no FE FE FE was sent

        const app = await newApp(ctx.link);
        const result = await app.protocol.getSettings();
        assert.equal(result.ok, true, JSON.stringify(result));
        assert.ok(ctx.firmware.sessionCounter > firstSession);
        assert.equal(ctx.firmware.gunMode, 'docked');
    } finally {
        await teardown(ctx);
    }
});

test('re-dock while the firmware waits for an ACK from the vanished App', async () => {
    const ctx = await setup();
    try {
        // The first App disappears in the middle of the settings stream.
        let responses = 0;
        ctx.link.filterToApp = (bytes) => {
            if (bytes.length > 7 && (bytes[2] & 3) === 1 && bytes[3] === C.sGetSettings && ++responses === 3) {
                ctx.link.toApp = null;
                return null;
            }
            return bytes;
        };
        const first = ctx.app.protocol.getSettings();
        assert.ok(await waitUntil(() => responses >= 3));
        ctx.link.filterToApp = null;

        const app = await newApp(ctx.link);
        const result = await app.protocol.getSettings();
        assert.equal(result.ok, true, JSON.stringify(result));
        assert.equal((await first).ok, false);
    } finally {
        await teardown(ctx);
    }
});

test('a slow first reply: the App dock retry does not restart the session (Qt App and web app)', async () => {
    const link = new MemoryLink();
    const firmware = new MockFirmware(S, link);
    firmware.start();
    try {
        // Every board-information reply reaches the App 900 ms late, so the App sends
        // its dock retry (750 ms) while the firmware is still waiting for the ACK.
        link.filterToApp = (bytes) => {
            if (bytes.length > 7 && (bytes[2] & 3) === 1 && bytes[3] === C.sDock2) {
                const late = Uint8Array.from(bytes);
                setTimeout(() => { if (link.toApp) link.toApp(late); }, 900);
                return null;
            }
            return bytes;
        };
        const app = await newApp(link);
        const result = await app.protocol.getSettings();
        link.filterToApp = null;
        assert.equal(result.ok, true, JSON.stringify(result));
        assert.equal(firmware.sessionCounter, 1, 'the dock retry of the same App must not start a new session');
        assert.equal(firmware.sessionActive, true);
        assert.equal(firmware.gunMode, 'docked');
    } finally {
        link.connected = false;
        await firmware.stop();
    }
});

test('WebSocket client lost ends the session and restores Run mode', async () => {
    const ctx = await setup({ over: 'web' });
    try {
        assert.equal((await ctx.app.protocol.getSettings()).ok, true);
        closePage(ctx, ctx.app);
        assert.ok(await waitUntil(() => !ctx.firmware.sessionActive && ctx.firmware.gunMode === 'run'));

        const app = await newApp(ctx.link);
        const started = Date.now();
        assert.equal((await app.protocol.getSettings()).ok, true);
        assert.ok(Date.now() - started < 700, 'the first dock attempt succeeds');
    } finally {
        await teardown(ctx);
    }
});

test('client lost during calibration restores the profile and unwinds', async () => {
    const ctx = await setup({ over: 'web' });
    try {
        const { protocol, events, transport } = ctx.app;
        assert.equal((await protocol.getSettings()).ok, true);
        await protocol.sendCommand(C.sCaliProfile, Uint8Array.of(C.sCaliStart, 1, 0));
        assert.ok(await waitUntil(() => events.some((e) => e.command === C.sCaliStageUpd)));
        for (let stage = 1; stage <= 3; ++stage) {
            ctx.firmware.trigger = true;
            assert.ok(await waitUntil(() => events.some((e) => e.command === C.sCaliStageUpd && e.payload[0] === stage)));
        }
        closePage(ctx, ctx.app);
        assert.ok(await waitUntil(() => ctx.firmware.gunMode === 'run' && !ctx.firmware.sessionActive));
        assert.equal(ctx.firmware.getProfileI32(1, 0), 11, 'offsets restored');

        const app = await newApp(ctx.link);
        assert.equal((await app.protocol.getSettings()).ok, true);
    } finally {
        await teardown(ctx);
    }
});

test('client lost with a pending save keeps the board docked and asks to save again', async () => {
    const ctx = await setup({ over: 'web' });
    try {
        const { protocol } = ctx.app;
        const loaded = await protocol.getSettings();
        ctx.firmware.failNextSave = true;
        assert.equal((await protocol.commitSettings(protocol.codec.cloneConfig(loaded.config), loaded.config)).ok, false);

        closePage(ctx, ctx.app);
        assert.ok(await waitUntil(() => !ctx.firmware.sessionActive));
        assert.equal(ctx.firmware.gunMode, 'docked');

        const app = await newApp(ctx.link);
        assert.equal((await app.protocol.getSettings()).ok, true);
        assert.ok(await waitUntil(() => app.events.some((e) =>
            e.command === C.sError && e.payload[0] === 0x82 && e.payload[1] === C.sGetProfile)));
        assert.equal(app.protocol.commitNeedsRetry(), true);
    } finally {
        await teardown(ctx);
    }
});

test('dock bytes inside frame payloads never trigger a re-dock', async () => {
    const ctx = await setup();
    try {
        const { protocol } = ctx.app;
        const loaded = await protocol.getSettings();
        const current = protocol.codec.cloneConfig(loaded.config);
        // Values made of 01 02 byte pairs.
        current.settings[S.settingsTypes_e.rumbleInterval] = 0x0201;
        current.settings[S.settingsTypes_e.customLEDcolor1] = 0x02010201;
        current.tinyUSB = { id: 0x0201, name: '' };
        const sessions = ctx.firmware.sessionCounter;
        const result = await protocol.commitSettings(current, loaded.config);
        assert.equal(result.ok, true);
        assert.equal(ctx.firmware.sessionCounter, sessions);
        assert.equal(ctx.firmware.getSetting(S.settingsTypes_e.customLEDcolor1), 0x02010201);
    } finally {
        await teardown(ctx);
    }
});

// ===== Web configuration mode: serial port and WebSocket together ============

async function roundTrip(protocol) {
    const loaded = await protocol.getSettings();
    assert.equal(loaded.ok, true, JSON.stringify(loaded));
    const current = protocol.codec.cloneConfig(loaded.config);
    current.settings[S.settingsTypes_e.rumbleInterval] = 123;
    const saved = await protocol.commitSettings(current, loaded.config);
    assert.equal(saved.ok, true, JSON.stringify(saved));
    return loaded;
}

test('web mode: an App on the serial port (Qt App, site) works when no page is connected', async () => {
    const ctx = await setup({ over: 'serial', webMode: true });
    try {
        await roundTrip(ctx.app.protocol);
        assert.equal(ctx.firmware.sessionLink, 'serial');
        assert.equal(ctx.firmware.getSetting(S.settingsTypes_e.rumbleInterval), 123);
        await ctx.app.protocol.disconnect();
        assert.ok(await waitUntil(() => ctx.firmware.gunMode === 'run' && !ctx.firmware.sessionActive));
    } finally {
        await teardown(ctx);
    }
});

test('web mode: a docked page refuses the serial App, which docks after the page leaves', async () => {
    const ctx = await setup({ over: 'web' });
    try {
        const page = ctx.app.protocol;
        await page.getSettings();
        const sessions = ctx.firmware.sessionCounter;

        const serialApp = await newApp(ctx.serialLink);
        const refused = await serialApp.protocol.getSettings();
        assert.equal(refused.ok, false);
        assert.equal(refused.error, 'dock_timeout');

        // The page session was not disturbed by the refused dock attempts.
        assert.equal(ctx.firmware.sessionLink, 'web');
        assert.equal(ctx.firmware.sessionCounter, sessions);
        await page.disconnect();
        assert.ok(await waitUntil(() => ctx.firmware.gunMode === 'run' && !ctx.firmware.sessionActive));

        // The retries sent while the page was docked were discarded: no stale session.
        await sleep(300);
        assert.equal(ctx.firmware.sessionActive, false);
        assert.equal(ctx.firmware.gunMode, 'run');

        await roundTrip(serialApp.protocol);
        assert.equal(ctx.firmware.sessionLink, 'serial');
    } finally {
        await teardown(ctx);
    }
});

test('web mode: a docked serial App refuses the page, and a closing page does not touch it', async () => {
    const ctx = await setup({ over: 'serial', webMode: true });
    try {
        const serialApp = ctx.app.protocol;
        await serialApp.getSettings();
        const sessions = ctx.firmware.sessionCounter;

        const page = await newApp(ctx.webLink);
        const refused = await page.protocol.getSettings();
        assert.equal(refused.ok, false);
        assert.equal(refused.error, 'dock_timeout');
        closePage(ctx, page);
        await sleep(200);

        assert.equal(ctx.firmware.sessionActive, true);
        assert.equal(ctx.firmware.sessionLink, 'serial');
        assert.equal(ctx.firmware.sessionCounter, sessions);
        await roundTrip(serialApp); // the serial session still works

        await serialApp.disconnect();
        assert.ok(await waitUntil(() => ctx.firmware.gunMode === 'run' && !ctx.firmware.sessionActive));
        const nextPage = await newApp(ctx.webLink);
        await roundTrip(nextPage.protocol);
        assert.equal(ctx.firmware.sessionLink, 'web');
    } finally {
        await teardown(ctx);
    }
});

test('web mode: a dock that nobody answers does not block the other link', async () => {
    const ctx = await setup({ over: 'web' });
    try {
        await ctx.app.protocol.disconnect();
        // Something on the serial port sends the dock handshake and never answers.
        ctx.serialLink.appWrite(Uint8Array.of(C.sDock1, C.sDock2));
        assert.ok(await waitUntil(() => ctx.firmware.sessionActive && ctx.firmware.sessionLink === 'serial'));
        assert.ok(await waitUntil(() => !ctx.firmware.sessionActive && ctx.firmware.gunMode === 'run', 5000),
                  'the unanswered session ends after the board-information retries');

        const page = await newApp(ctx.webLink);
        await roundTrip(page.protocol);
        assert.equal(ctx.firmware.sessionLink, 'web');
    } finally {
        await teardown(ctx);
    }
});

test('web mode: docked with a pending save, an App on the other link is asked to save again', async () => {
    const ctx = await setup({ over: 'web' });
    try {
        const page = ctx.app.protocol;
        const loaded = await page.getSettings();
        ctx.firmware.failNextSave = true;
        assert.equal((await page.commitSettings(page.codec.cloneConfig(loaded.config), loaded.config)).ok, false);
        closePage(ctx, ctx.app);
        assert.ok(await waitUntil(() => !ctx.firmware.sessionActive));
        assert.equal(ctx.firmware.gunMode, 'docked');

        const serialApp = await newApp(ctx.serialLink);
        assert.equal((await serialApp.protocol.getSettings()).ok, true);
        assert.equal(ctx.firmware.sessionLink, 'serial');
        assert.ok(await waitUntil(() => serialApp.events.some((e) =>
            e.command === C.sError && e.payload[0] === 0x82 && e.payload[1] === C.sGetProfile)));
    } finally {
        await teardown(ctx);
    }
});
